app/blog/urls.py
from . import views
from .apps import BlogConfig

from django.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_by_tag"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/share/", views.PostShareView.as_view(), name="post_share"),
]

app/django_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
]

app/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Черновой вариант"),
        ("published", "Опубликованный"),
    )
    title = models.CharField(max_length=256, verbose_name="Загаловок")
    slug = models.SlugField(max_length=256, unique_for_date="publish", verbose_name="Семантический URL")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts", verbose_name="Автор")
    tags = TaggableManager()
    body = models.TextField(verbose_name="Содержание")
    publish = models.DateTimeField(default=timezone.now, verbose_name="Дата и время публикации статьи")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания статьи")
    updated = models.DateTimeField(auto_now=True, verbose_name="Дата и время обновления статьи")
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default="draft", verbose_name="Статус публикации")

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ("-publish", )
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80, verbose_name="Имя")
    email = models.EmailField(verbose_name="E-mail")
    body = models.TextField(verbose_name="Содержание")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания статьи")
    updated = models.DateTimeField(auto_now=True, verbose_name="Дата и время обновления статьи")
    active = models.BooleanField(default=True, verbose_name="Активность статьи")

    class Meta:
        ordering = ("created", )
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

app/blog/forms.py
from . import models

from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ("name", "email", "body")

app/blog/views.py
from . import models
from . import forms
from django_blog import settings

from django.db.models import Count
from django.core import mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from django.views import generic
from django.shortcuts import render, redirect, reverse
from django.shortcuts import get_object_or_404

from taggit.models import Tag


class PostListView(generic.View):
    def get(self, request, tag_slug=None):
        page_number = request.GET.get("page", 1)
        object_list = models.Post.published.all()

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            object_list = object_list.filter(tags__in=[tag])

        paginator = Paginator(object_list, 3)
        page = paginator.get_page(page_number)

        context = {
            "page": page,
        }

        return render(request, "blog/post/list.html", context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(models.Post, slug=post, status="published", publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = None

    if request.method == "POST":
        comment_form = forms.CommentPostForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = forms.CommentPostForm()
    
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = models.Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by("-same_tags", "-publish")[:4]
    
    context = {
        "post": post,
        "comments": comments,
        "new_comment": new_comment,
        "comment_form": comment_form,
        "similar_posts": similar_posts,
    }

    return render(request, "blog/post/detail.html", context)


class PostShareView(generic.View):
    template_name = "blog/post/share.html"

    def get(self, request, post_id):
        post = get_object_or_404(models.Post, id=post_id, status="published")
        form = forms.EmailPostForm()

        context = {
            "post": post,
            "form": form,
        }

        return render(request, self.template_name, context)

    def post(self, request, post_id):
        post = get_object_or_404(models.Post, id=post_id, status="published")
        form = forms.EmailPostForm(request.POST)

        if form.is_valid():
            cleaned_data = form.cleaned_data
            message = f"\"{post.title}\" was succesfuly sent to {cleaned_data['to']}."
            self.__send_mail(request, post, cleaned_data)
            messages.add_message(request, messages.INFO, message)

        return redirect(reverse("blog:post_share", args=[post_id]))
    
    def __send_mail(self, request, post, cleaned_data):
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cleaned_data['name']} ({cleaned_data['email']}) recommendsyou reding {post.title}"
            body = f"Read \"{post.title}\" at {post_url}\n\n{cleaned_data['name']}'s comments: {cleaned_data['comments']}."
            mail.send_mail(subject, body, settings.EMAIL_HOST_USER, [cleaned_data["to"]])

app/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
    <title> {% block title %}{% endblock %} </title>
</head>

<body>

    <div>
        {% block content %}{% endblock %}
    </div>

</body>

</html>

app/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}"> Previous </a>
        {% endif %}
    </span>
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}"> Next </a>
    {% endif %}
</div>

app/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}

    <h1> {{ post.title }} </h1>
    <p> Published {{ post.publish }} by {{ post.author }} </p>
        {% if post.tags.all %}
            <p> Tags: {{ post.tags.all|join:", " }} </p>
        {% endif %}
    <p> {{ post.body|linebreaks }} </p>
    <p> <a href="{% url 'blog:post_share' post.id %}"> Share this post </a> </p>

    <h2> Рекомендации: </h2>

    {% for post in similar_posts %}
        <h2><a href="{{ post.get_absolute_url }}"> {{ post.title }} </a></h2>
        <p> Published {{ post.publish }} by {{ post.author }} </p>
        {% if post.tags.all %}
            <p>
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag %}"> #{{ tag.name }} </a>
                {% endfor %}
            </p>
        {% endif %}
        <p> {{ post.body|truncatewords:30|linebreaks }} </p>
    {% endfor %}

    {% with comments.count as total_comments %}
        {% if total_comments <= 1 and total_comments != 0 %}
            <h2> {{ total_comments }} комментарий </h2>
        {% elif total_comments <= 4 and total_comments != 0 %}
            <h2> {{ total_comments }} комментария </h2>
        {% else %}
            <h2> {{ total_comments }} комментариев </h2>
        {% endif %}
    {% endwith %}

    {% for comment in comments %}
        <p> [{{ forloop.counter }}] [{{ comment.created }}] {{ comment.name }}: {{ comment.body }} </p>
    {% endfor %}

    {% if new_comment %}
        <h2> Your comment has been added. </h2>
    {% else %}
        <h2> Add a new comment </h2>
        <form action="." method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

app/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %} Post List {% endblock %}

{% block content %}

    <h1> Post List: </h1>

    {% for post in page.object_list %}
        <h2><a href="{{ post.get_absolute_url }}"> {{ post.title }} </a></h2>
        <p> Published {{ post.publish }} by {{ post.author }} </p>
        {% if post.tags.all %}
            <p>
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag %}"> #{{ tag.name }} </a>
                {% endfor %}
            </p>
        {% endif %}
        <p> {{ post.body|truncatewords:30|linebreaks }} </p>
    {% endfor %}

    {% include "blog/pagination.html" %}

{% endblock %}

app/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a post {% endblock %}

{% block content %}

    <h1> Share "{{ post.title }}" by e-mail </h1>

    {% if messages %}
        {% for message in messages %}
            <p> {{ message }} </p>
        {% endfor %}
    {% endif %}

    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send e-mail">
    </form>

{% endblock %}